name: PAckage Configuration Tests

on:
  workflow_call:
    inputs:
      command:
        description: "The command to run for testing the package configuration."
        required: false
        type: string
        default: task test:config

permissions:
  contents: read

env:
  FLOX_DISABLE_METRICS: true

jobs:
  test-config:
    name: Configuration Tests
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout source code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Install Flox
        uses: flox/install-flox-action@6e70b2624cea62b0f11ea4a28e719fe1c86c028b # v2.4.1
      
      - name: Run configuration tests
        uses: flox/activate-action@7065dcbe5583b7b015f07a8ebd49d7266e3053e8 # v1.1.1
        with:
          command: ${{ inputs.command }}
