name: PAckage Configuration Tests

on:
  workflow_call:
    inputs:
      command:
        description: "The command to run for testing the package configuration."
        required: false
        type: string
        default: task test:config

permissions:
  contents: read

env:
  FLOX_DISABLE_METRICS: true

jobs:
  test-config:
    name: Configuration Tests
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout source code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install Flox
        uses: flox/install-flox-action@8c71d71672ea52e1494b168ac0f27d46b96068be # v2.5.2
      
      - name: Run configuration tests
        uses: flox/activate-action@7065dcbe5583b7b015f07a8ebd49d7266e3053e8 # v1.1.1
        with:
          command: ${{ inputs.command }}
